### ISSUE TITLE
カラーバリエーションを増やす

### ISSUE THREAD

**Issue by s-take** [chubby-road/rouletto-react-app#2]
4人以上になると同じ色の人が出てきちゃう

**Comment by chubby-road** [comment]
色を追加するのは簡単っす。
難しいのは文字色と背景色のセットで見栄えが悪くない（あえて良いとは書かないですｗ）・見にくくない組み合わせをある程度の数探すことかなと思います。
人数が多くなったら同じ色の人が出ちゃうのはある程度許容しないと厳しい気がします。

**Comment by s-take** [comment]
ですね。ちょっとこのissueはクローズします
